# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'W3Firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for W3Firebase


  target 'W3FirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'W3FirebaseUITests' do
    # Pods for testing
  end

end
